language: ruby
sudo: false

addons:
  apt:
    packages:
      - chromium-chromedriver
      
before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

notifications:
  email: false

rvm:
  - 2.5.1

env:
 - "BLACKLIGHT_VERSION='~>7.0' RAILS_VERSION=5.2.2"
 - "BLACKLIGHT_VERSION='~>6.0' RAILS_VERSION=5.2.2"
 - "RAILS_VERSION=5.1.6"

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
